// <auto-generated />
namespace Expense_Tracker.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Createdatabaseforexpensetracker : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Createdatabaseforexpensetracker));
        
        string IMigrationMetadata.Id
        {
            get { return "202302090451518_Create database for expense tracker"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
